version: '3.7'

services:
  redis:
    image: redis:7.2
    container_name: redis
    command: redis-server
    restart: on-failure
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
  db:
    image: postgres:15
    container_name: db
    restart: on-failure
    env_file:
      - .env.docker
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
  app:
    build: .
    container_name: app
    ports:
      - '8000:8000'
    env_file:
      - .env.docker
    restart: always
    depends_on:
      - redis
      - db

volumes:
  dbdata:
  redisdata: